"""
Django settings for openvpnathome project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

from .development import *
from .secret import *
from .installed_apps import *
from .middleware import *
from .templates import *
from .constance import *
from .restframework import *
from .auth import *
from .locale import *
from .database import *
from .static import *
from .email import *

ROOT_URLCONF = 'openvpnathome.urls'
WSGI_APPLICATION = 'openvpnathome.wsgi.application'


try:
    from openvpnathome.config import ALLOWED_HOSTS
except:
    ALLOWED_HOSTS = ['*']

try:
    from openvpnathome.config import INTERNAL_IPS
except:
    INTERNAL_IPS = ['127.0.0.1']
