# Generated by Django 2.1.2 on 2018-12-15 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='email_from',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='email_smtp_login',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='email_smtp_password',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='email_smtp_port',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='email_smtp_server',
        ),
    ]
