# Generated by Django 2.1.2 on 2018-12-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20181215_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='BlockListUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
