# Generated by Django 2.1.2 on 2018-12-22 00:02

from django.db import migrations


HOSTS_URLS = (
    {'url': 'https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts', 'enabled': True},
    {'url': 'https://mirror1.malwaredomains.com/files/justdomains', 'enabled': False},
    {'url': 'http://sysctl.org/cameleon/hosts', 'enabled': False},
    {'url': 'https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist', 'enabled': False},
    {'url': 'https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt', 'enabled': False},
    {'url': 'https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt', 'enabled': False},
    {'url': 'https://hosts-file.net/ad_servers.txt', 'enabled': False}
)


def add_hosts_sources(apps, schema_editor):
    BlockListUrl = apps.get_model('management', 'BlockListUrl')
    for entry in HOSTS_URLS:
        BlockListUrl.objects.create(**entry)


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_add_dns_blocked_domains'),
    ]

    operations = [
        migrations.RunPython(add_hosts_sources),
    ]
