# Generated by Django 2.2.9 on 2019-12-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x509', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ca',
            name='passphrase',
            field=models.CharField(blank=True, help_text='Passphrase for the private key, if present', max_length=64),
        ),
        migrations.AddField(
            model_name='cert',
            name='passphrase',
            field=models.CharField(blank=True, help_text='Passphrase for the private key, if present', max_length=64),
        ),
    ]
