# Generated by Django 2.0.1 on 2018-02-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='protocol',
            field=models.CharField(choices=[('udp', 'UDP'), ('tcp', 'TCP')], default='udp', max_length=10),
        ),
    ]
