# Generated by Django 2.0 on 2018-01-04 22:12

import django.core.validators
from django.db import migrations, models


def create_settings(apps, schema_editor):
    Settings = apps.get_model('management', 'Settings')
    Settings.objects.create(pk=1)


def remove_settings(apps, schema_editor):
    Settings = apps.get_model('management', 'Settings')
    Settings.objects.delete(pk=1)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=False)),
                ('email_from', models.EmailField(blank=True, default='', max_length=128)),
                ('email_smtp_server', models.CharField(blank=True, default='', max_length=128)),
                ('email_smtp_port', models.IntegerField(default=465, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('email_smtp_login', models.CharField(blank=True, default='', max_length=128)),
                ('email_smtp_password', models.CharField(blank=True, default='', max_length=128)),
                ('registration_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'settings',
                'verbose_name': 'settings',
            },
        ),
        migrations.RunPython(create_settings, remove_settings)
    ]
