Document: openvpnathome
Title: Debian openvpnathome Manual
Author: <insert document author here>
Abstract: This manual describes what openvpnathome is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openvpnathome/openvpnathome.sgml.gz

Format: postscript
Files: /usr/share/doc/openvpnathome/openvpnathome.ps.gz

Format: text
Files: /usr/share/doc/openvpnathome/openvpnathome.text.gz

Format: HTML
Index: /usr/share/doc/openvpnathome/html/index.html
Files: /usr/share/doc/openvpnathome/html/*.html
