# Generated by Django 2.0.1 on 2018-06-24 18:51

from django.db import migrations
import vpnathome.apps.openvpn.models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='network',
            field=vpnathome.apps.openvpn.models.NetworkAddressField(default='172.30.0.0/16', max_length=100, null=True),
        ),
    ]
