# Generated by Django 2.1.2 on 2018-12-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0004_auto_20181215_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
